//!!NODE_ROOT <chapter>
[."topic"]
[[introduction,introduction.title]]
= Introduction
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:idprefix:
:idseparator: -
:sourcedir: .
:info_doctype: chapter
:info_title: Introduction
:info_abstract: Learn best practices for operating EKS clusters.

[abstract]
--
Learn best practices for operating EKS clusters.
--

Welcome to the EKS Best Practices Guides. The primary goal of this
project is to offer a set of best practices for day 2 operations for
Amazon EKS. We elected to publish this guidance to GitHub so we could
iterate quickly, provide timely and effective recommendations for
variety of concerns, and easily incorporate suggestions from the broader
community.

## What is AsciiDoc?

AsciiDoc is a lightwieght markup language used for writing documentaion, articles, books, and more. It allows authors to create plain text documments with simple and readable syntax that can be converted into various formats, such as HTML, PDF, and DocBook. AsciiDoc is particulary popular in technical writing and software development due to its support for the following elements:

* Code bocks
* Tables
* Lsits
* Images
* Footnoots

The language's flexibility and ease of use make it a preferred choice for creating structured and well-formatted contet.

## What is GitHub?

GitHub is a web-based platform that provides version contorl and collaborative tools for software development projects. It is built around Git, a distributed version control system that allows multiple developers to work on a project simultaneosly without overwriting each other's changes. GitHub offers a range of featuers, including:

* Issue tracking
* Project managemnt
* Code revieew
* Continuous intregration

These features help streamline the development process and enhance collaboration among team members. GitHub also hosts open-source projects, enabling developers to contribute to and benefit from a vast repositry of shared code and resources.


We currently have published guides for the following topics:

* xref:networking[Networking]
* xref:cluster-upgrades[Cluster Upgrades]

We also open sourced a Python based CLI (Command Line Interface) called
https://github.com/aws-samples/hardeneks[hardeneks] to check some of the
recommendations from this guide.

In the future we will be publishing best practices guidance for
performance, cost optimization, and operational excellence.

== Related guides

In addition to the
https://docs.aws.amazon.com/eks/latest/userguide/what-is-eks.html[EKS
User Guide], AWS has published several other guides that may help you
with your implementation of EKS.

* https://aws.github.io/aws-emr-containers-best-practices/[EMR
Containers Best Practices Guides]
* https://awslabs.github.io/data-on-eks/[Data on EKS]
* https://aws-observability.github.io/observability-best-practices/[AWS
Observability Best Practices]
* https://aws-ia.github.io/terraform-aws-eks-blueprints/[Amazon EKS
Blueprints for Terraform]
* https://aws-quickstart.github.io/cdk-eks-blueprints/[Amazon EKS
Blueprints Quick Start]

== Contributing

We encourage you to contribute to these guides. If you have implemented
a practice that has proven to be effective, please share it with us by
opening an issue or a pull request. Similarly, if you discover an error
or flaw in the guidance we've already published, please submit a PR to
correct it. The guidelines for submitting PRs can be found in our
https://github.com/aws/aws-eks-best-practices/blob/master/CONTRIBUTING.md[Contributing
Guidelines].
